### ISSUE TITLE
Microsite Changes

### ISSUE THREAD

**Issue by CitizensMedia** [the-cm/cm-next#1]
1. Go back to limited amount of 'About' info, then 'More/Less'
2. Hide video – make a dropdown panel like in CMS
3. Hide pic snippits. Hide Gallery – make a dropdown panel like in CMS
4.  Bring Kudos back to right sidebar (mobile version will need this incorporated somehow). 
   - Include link to 'Give Kudos'
5. Make 'Linked Projects' a dropdown panel
6. Replace the term _Microsite_ with _Projects_ everywhere.

ADD 'Edit' links on each item. Point to specific locations e.g. clicking 'Edit' on video/audio section takes user to video section in microsite CMS.

**Comment by CitizensMedia** [comment]
Replace the term 'Microsite' with 'Projects' (i.e. throughout)

**Comment by CitizensMedia** [comment]
More on Microsites/Projects - TOP LINKS
1. Change 'Where' to 'Map'
1b. In 'Location' add 'Global' as an option. In 'Map' state 'This project is global.'
2. Ditch Reviews and Promotions http://thecitizensmedia.com/cms/blog/create/start
3. Change 'Start a Discussion' back to 'Ask a Question' ('Forum' Changes to 'Q&A')
4. In CMS, change 'Jobs' to 'Needs' - add Needs as a link. Include link for 'Post a Need'
5. Add 'Assets': need to add this to Microsite CMS. Message. Will propose how we do this in another comment.
6. In 'Blogs' http://thecitizensmedia.com/pub/group/impact-economy?id=132;at=blogs, ditch 'Post a Promotion' and 'Post a Job'

**Comment by CitizensMedia** [comment]
Member Profiles. 
1. Hide video and gallery in tabs, as per Microsites
2. Integrate 'Follow' detail to main 'About' page
3. Add 'Location' - move 'Community' from main 'About' page here
4. 'Joined On' from About' page can go
5. Add Q&A tab - as per Microsites

**Comment by CitizensMedia** [comment]
Ditch Location Profiles: http://thecitizensmedia.com/cms/group/microsite/location_profile_edit?id=121 (at last?!.. sorry)

**Comment by CitizensMedia** [comment]
Ditch the form on 'About' page on Microsites - we created these for the Butterfly Project - all seem obsolete now.

**Comment by CitizensMedia** [comment]
We need to make sure we don't have too many links as limited width between browsers

1- 'Needs' and 'Assets' could come under the title link 'Exchange'
2 - We can call Etsy / online shop stuff 'Marketplace' and add this beneath same tab

**Comment by CitizensMedia** [comment]
Replace the 'Start a Discussion' (above 'About' info / beneath follow links) with 'Give Kudos!'

**Comment by CitizensMedia** [comment]
Also note https://github.com/the-cm/cm-next/issues/9

= adding 'Invest' link at top (next to 'Like')

**Comment by CitizensMedia** [comment]
Ref. including **Needs**, **Offers** (and at some point maybe **Marketplace**) under link tab **Exchange** – from @TiberiusB comment: https://github.com/the-cm/cm-next/issues/8 – call **Resources** instead.

**Comment by CitizensMedia** [comment]
![screenshot_83](https://cloud.githubusercontent.com/assets/5413780/11115610/a160ade0-88e1-11e5-9b64-e26bc1b52d12.png)

**Comment by CitizensMedia** [comment]
To workflow, add 'What best describes you? Solution / Community Project'
(we will want to be able to list microsites by selection of the above, then search by tags)

**Comment by mu-is-too-short** [comment]
We'll go over this again and redo.
