### ISSUE TITLE
Add 'type' to microsites + edit questions

### ISSUE THREAD

**Issue by CitizensMedia** [the-cm/cm-next#17]
Will feed into new microsite layout Issue #1 (same idea as adding blog types--Issue #16 )
Please change questions and messages as follows:
![screenshot_100](https://cloud.githubusercontent.com/assets/5413780/11332395/35df472e-917a-11e5-9f29-60afe533702a.png)

**Comment by CitizensMedia** [comment]
Public display of questions:
![screenshot_101](https://cloud.githubusercontent.com/assets/5413780/11332693/a714f1f8-917c-11e5-9c8c-b08b36da8321.png)

**Comment by mu-is-too-short** [comment]
I can't figure out how to nicely format that sub-headers in the public side of things so I'll leave that alone for now. And everything goes on the main microsite page until I reorganize the tabs.
