### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by CitizensMedia** [the-cm/cm-next#18]
Please add tagging functionality to Q&A

Add tagging tip in open fields... something like:
![screenshot_102](https://cloud.githubusercontent.com/assets/5413780/11333005/5fa7ec00-917f-11e5-8059-52ad2e8b1464.png)
Message: Tagging: type **@name** to mention others

**Comment by mu-is-too-short** [comment]
Adding this means dropping the HTML editor for Q&A.

**Comment by CitizensMedia** [comment]
hum. I guess considering mobile is key for usability I'd better get used to less HTML
