### ISSUE TITLE
Defining Microsite Members

### ISSUE THREAD

**Issue by CitizensMedia** [the-cm/cm-next#23]
In CMS this:
![screenshot_131](https://cloud.githubusercontent.com/assets/5413780/12382072/b5dac52e-bd4a-11e5-8a0a-052301538a46.png)
with:
Title: **Membership requests**
Message: 
What are the terms for being a member?
_Example: "To be a member you must live in our community."_

Give starter prompt **To be a member you must...**

Starter prompt along with publishers terms should appear as a message at the top of public membership page.

**Comment by mu-is-too-short** [comment]
This will be replaced by the "if you're in this community then you're a microsite member" logic.
