### ISSUE TITLE
Modules in Microsite Forums 

### ISSUE THREAD

**Issue by CitizensMedia** [the-cm/cm-next#24]
please can you make it so modules set up for Microsites appear on the Forum pages? Thanks :) 

e.g.http://www.bergnekcommunityprojects.org/pub/qa/bergnek-community-projects-cooperative?id=127

**Comment by mu-is-too-short** [comment]
This was sorted out during the first round of microsite layout cleanups, all the Q&A pages should now look like all the other microsite pages (including modules).
