### ISSUE TITLE
Final on update on Microsite Stuff 

### ISSUE THREAD

**Issue by CitizensMedia** [the-cm/cm-next#27]
Ditch 'Offer' as a blog type (= 'Solution')

Here's google doc that details how I think the Microsite Home Pages should go.
https://docs.google.com/document/d/14WzKbULS0j9t8EFgo6Pg8OYUnOCoq27cbLM2P0E34lI/edit?usp=sharing

**Comment by mu-is-too-short** [comment]
I merged the *Where* tab into *About* and tried to clean up the *About* with some toggling panels for the video, gallery, map, and linked microsites to cut down on the clutter.

**Comment by CitizensMedia** [comment]
looking good :+1: 
thank u!
