### ISSUE TITLE
Draft Blogs 'closing page' and management for posting new blogs 

### ISSUE THREAD

**Issue by CitizensMedia** [the-cm/cm-next#28]
from email 
you get to this page (1st attachment) after deleting a draft blog, or saving a draft
![screen shot 2016-02-22 at 10 34 21 pm](https://cloud.githubusercontent.com/assets/5413780/13243863/eb33a2a8-d9b6-11e5-849e-623b96128d2b.png)
thinking it should just take user to their account page

<s>Ditch ability to post blogs across multiple microsites</s>

As we are going Microsite centric, also need to make it so a blog post has to be attached to a particular microsite. We may want to do this by only making 'Post a new blog' functionality available from a microsite. If we do this, we'll want to perhaps delete 'Post a new Microsite' and 'Post a new Blog' on profile pages. We'll also need to change 'Your microsites' to 'Microsites you're in', and add ability to 'Start a New Microsite' and 'Search Microsites' from there.
![screen shot 2016-02-22 at 10 40 06 pm](https://cloud.githubusercontent.com/assets/5413780/13243906/1901983e-d9b7-11e5-968e-e9268bee6c74.png)

**Comment by CitizensMedia** [comment]
change blog approval process such that all blogs must be approved by the applicable administrators of a microsite before being published (as opposed to the first 5 blogs needing approval from CM central)

**Comment by mu-is-too-short** [comment]
Drop the approval number to three blogs and leave it up to the site admins for now.
