### ISSUE TITLE
Kudos: ideas for how this should work

### ISSUE THREAD

**Issue by CitizensMedia** [the-cm/cm-next#29]
We're going to make it so blogs can only be posted from a particular Microsite. People will not be able to post the same blog on different microsites. This is because it's too confusing, and we also think 'Kudos' should be given to Microsites and not to individuals. I discussed this idea with Eric this afternoon: Microsite members will be notified when Kudos has been given to that Microsite. Kudos will be distributed to Members according to the number of points earned. $10 = 10 points. Points maybe earned by posting blogs, getting likes etc. The number of points a member has will be indicated by a colour badge, which will appear next to their name on the Microsite member page.

That's the idea, but we won't set in concrete till we can test the idea. As mentioned, CM would like to give $500 worth of Kudos to content being generated on the Bergnek Microsite. Keith: the intention is that this will help to pay for internet access. We can send the funds over through Warren. Suggest we decide on certain things that will earn a share of the CAD$500 (5,558 ZAR), say: $1 for posting a blog; $1 for every 20 views on a blog; $1 for every 5 likes; $0.25 for every comment posted on one of your blogs.

When I3 gets going, it will pledge Kudos on Project Microsites it wants to support. The idea is that this will help in generating activity. We can invite people at Sensorica, MAN etc to help members earn Kudos and to better understand Bergnek people and projects, by reading blogs, sharing, liking and posting comments. They will be able to earn Kudos themselves by joining the microsite and posting blogs suggesting ways they can help. We might want to make it so the principle administrator of a microsite (this is Warren for Bergnek) must approve blogs before they are posted.

**Comment by WarrenTB** [comment]
> wants

change to 'agrees to support...'

Funds should be displayed as both $ and R so that a local person knows what it means to them.

Yes blogs should be approved be fore posted. Lots of experience with spammers in the blog realm

**Comment by CitizensMedia** [comment]
you won't get spam so far as CM logins will stop that - no-one can write a blog without a cm login and the first 5 blogs a member posts must be approved by CM. To post a blog on Bergnek Microsite, they will also need to be accepted/approved as a member. The only reason I suggested adding the option to approve blogs is because of Kudos on Microsites being distributed to all content posted on the microsite. That said, maybe it makes sense to replace the CM approving blogs to microsite administrators. Not a top priority but it feels like the right way to go and makes management more scaleable.

**Comment by WarrenTB** [comment]
Got it. Ok that makes sense. 

---
Warren Te Brugge
Sent from my iPhone
📞 +1.858.869.9882
Manzimvula | Manzimvula eNews | My Arms Wide Open | My World In a Garden | Twitter

**Comment by CitizensMedia** [comment]
on the referring to R vs $. 'Points' =  'Comcoins'. We need to decide which term is best. I'm inclined to stick with Comcoins (community coins) but I maybe biased?! We need a universal term for a unit, then we can make unique agreements with Microsite owners about what Comcoins/points can be exchanged for. We can explain on the google doc we develop with Keith for getting Bergnek community members contributing content, that every Comcoin they earn gets them 11ZAR, which Keith will distribute. We also need to decide when to distribute. Am assuming Keith will be doing this in person. How might this work?

**Comment by WarrenTB** [comment]
I'd keep it simple and not use the exchange rate and say 1 Comcoins = R10. I agree stick with one universal term. 

---
Warren Te Brugge
Sent from my iPhone
📞 +1.858.869.9882
Manzimvula | Manzimvula eNews | My Arms Wide Open | My World In a Garden | Twitter

**Comment by CitizensMedia** [comment]
:+1: thx

**Comment by CitizensMedia** [comment]
@mu-is-too-short Final on Kudos: please change the default message i.e. the 'Give Kudos!' beneath microsite name to **Connect The Unconnected**

Messages of Kudos should appear on every page of a microsite (all blogs, forum etc) until the value's been used up.

Kudos will be pledged on Microsites for distribution among its members. Microsite members will be notified when Kudos has been given to that Microsite. Kudos will be distributed to members as Comcoins, which maybe earned by posting blogs, getting likes etc. $10 = 100 Comcoins. 

- C10 for posting a blog that gets published by the microsite administrator; 
- C10 for every 20 views on a blog; 
- C10 for every 8 likes on your blog posts, comments or answers in the forum; 
- C10 for every 4 comments posted on one of your blogs.

The number of Comcoins a member has been issued will be indicated by a colour badge, which will appear next to their name against content they post on CM sites.

Supporters may target Kudos pledged to members of a particular community. For example, for Bergnek Community Projects, they might want to make it only gets distributed to the people of Bergnek.

Note: for blogs to be published, they must be approved by the administrators of the Microsite in which it’s intended to appear.
![screenshot_175](https://cloud.githubusercontent.com/assets/5413780/13552731/991f1f94-e323-11e5-9b63-59aa906d9121.png)
