### ISSUE TITLE
Add to Blog Types

### ISSUE THREAD

**Issue by CitizensMedia** [the-cm/cm-next#30]
please add 
1. Story
2. Project
to blog types
![screen shot 2016-02-23 at 12 33 59 am](https://cloud.githubusercontent.com/assets/5413780/13245950/7732d4c8-d9c5-11e5-93b8-1434b6b3d4be.png)
thanks!

**Comment by mu-is-too-short** [comment]
Actually, just remove the whole *Need*/*Solution* section.
