### ISSUE TITLE
Adding 'Invest' To Microsites

### ISSUE THREAD

**Issue by CitizensMedia** [the-cm/cm-next#31]
We need a simple **'Invest'** button on home page of Bergnek Microsite: take out the 'Ask a Question' button on the Microsite home pages and make this the 'Invest' button.

Then on blog posts, add a 1-liner to the foot of the blog 'Invest in <name of microsite>'.

Acts like another page in Microsite with link to*\* 'Back to <name of microsite>'**

**Invest Page** needs:
1) Open Paragraph
**What are people investing in? How are funds managed and distributed?**
_open para
links_

2) Investment Links
**Add links to the place people go to invest.**

3) Ability to embed a Mindomo map
User Message: **Add a Mindmap that shows where investments go and how they're connected. You can use Mindomo and embed it here, or add a link instead.**
https://www.mindomo.com/

**Comment by CitizensMedia** [comment]
@WarrenTB Do you think the proposed layout for donation page will work? 

Does Mindomo have embedding ability? 

What to call 'donate' button (donate, invest, support??)

**Comment by WarrenTB** [comment]
Sent a comment via email. Otherwise layout looks good. 

Opening paragraph on CM is great. Just can't change much on GlobalGiving. Didn't want to have to re-qualify multiple pages which means having to raise $4,000 in a month from a braid base of donors.

**Comment by CitizensMedia** [comment]
@WarrenTB Thanks and that sounds like a lot of tape! 

I say we stick with 'Invest'. The prompt question:
**What are people investing in? How are funds managed and distributed? Provide a brief explanation, then add links to investment opportunities below.**
_open para
links_

**Comment by CitizensMedia** [comment]
Looks like premium Mindomo members can grab an embed code. @mu-is-too-short will it be straight forward to do this? @WarrenTB do u agree about this idea? I'd love to explore how the projects already happening in Bergnek feed into each other. We can perhaps use the map to highlight 'Need' 'Solution and Challenge as 3 key headers for each project, and include a link to the blog post  Keith creates. Maybe another colour could be used on maps for needs not yet fulfilled that might inspire people. We could add a note inviting people to share ideas for how they can help by posting comments on the blogs.

**Comment by CitizensMedia** [comment]
@mu-is-too-short think we take out the 'Ask a Question' button on the Microsite home pages and make this the 'Invest' button. 

Then on blog posts, add a 1-liner to the foot of the blog 'Invest in <name of microsite>'. Could possibly add this to the bottom of comment threads too, but maybe too much and come across as to sales'ey?

Also - can we make the name of community on home page of Microsites open up location in google map in a thickbox (thickboxes work of on smartphones?)

Okay - so now I've really piled it on. Time to back off! I know it will take time to get to all this @WarrenTB

**Comment by mu-is-too-short** [comment]
That would probably be straight forward. I'd need to know what the embed codes look like so that I can see what they actually do. I'd also need to know where they'd show up on the site.
