### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by TiberiusB** [the-cm/cm-next#8]
I define them as different ways to look into the system. 
One example is a project-centric theme, where the user explores projects, for different reasons, to find something to do, to find something to take (get inspired from), to find something to invest in ($, time, ...), to compate with other projects. 
Another example is a people-centric theme, where the user is explores other users for different reasons, to find someone to do something, to see what someone is doing, to see how someone is related to someone else, etc. 
Another one is activity type/domain-centric, where the user explores what projects are in a certain domain, where to apply his skills, what domains are covered by the entire ecosystem and how different domains relate to each others, how active or popular certain domains are, ... ,  
You can also make one resource-centric, where the user is looking for some equipment or tool, to understand the total assets accessible to the entire ecosystem, how certain resources are used and where, why some resources are not used, if there is a need for a certain resource, ...

**Comment by CitizensMedia** [comment]
I like where you're going here @TiberiusB resource-centric makes sense – especially given the intention to directly connect this with SENSORICA NRP. Now that I'm describing the 'big vision' on Impact Economy site i.e. separating it from CM (the communications to commerce exchange component), I've been thinking about what to say for 'Why' on the-cm.com. 

This makes me think about how we can make it easy for people to build an NRP for whatever project they have. We need to give it a userflow that takes the user by the hand. Note resources include each others skills. You've definitely given some valuable food for thought!
